### ISSUE TITLE
태그 자동 완성을 위한 Trie 구현

### ISSUE THREAD

**Issue by Untaini** [khu-cloud-computing-team-h/SearchAPI#1]
## 요구사항
- 한글 태그를 저장할 수 있는 Trie 자료구조를 만든다.
- 한글은 초성, 중성, 종성으로 쪼개서 저장해야 한다.
- 자동완성 조회 성능을 올리기 위해 클라이언트가 보낸 prefix를 가진 한글 태그 목록을 빠르게 불러올 수 있는 기능이 필요하다.
- 한글 태그 리스트를 전달하면 완성된 Trie가 반환되는 기능을 구현한다.

**Comment by khw7385** [comment]
## 자료구조
### 트라이
```java
class Trie {
    Node root;
}
```
### 노드
```java
class Node{
    String data;
    boolean isLast;
    Map<Integer, Node> childNodes = new HashMap<>();
}
```

**Comment by Untaini** [comment]
@khw7385 
노드의 String data에는 어떤 값이 들어가나요?

**Comment by khw7385** [comment]
@Untaini 
태그의 마지막 노드일 때 태그의 값을 넣습니다. 예를 들어, 하늘의 경우 'ㄹ' 에 해당하는 노드에 하늘이라는 데이터가 들어갑니다. 나머지의 경우는 null 값입니다.

**Comment by Untaini** [comment]
> @Untaini 태그의 마지막 노드일 때 태그의 값을 넣습니다. 예를 들어, 하늘의 경우 'ㄹ' 에 해당하는 노드에 하늘이라는 데이터가 들어갑니다. 나머지의 경우는 null 값입니다.

그러면 data가 null이 아닌 경우와 isLast가 true인 경우는 항상 같은 건가요?

**Comment by khw7385** [comment]
맞습니다. isLast 는 마지막 노드를 나타내는 flag입니다. 마지막 노드일 때 data에 태그 값이 들어갑니다.
